- id: boa-restrictor
  name: Boa Restrictor Linter by Beyonder Deutschland
  description: A custom Python and Django linter by Beyonder Deutschland
  entry: boa-restrictor
  language: python
  types: [ python ]
